version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - database
    tty: true 
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    tty: true
  database:
    image: mongo
    ports:
      - '27017:27017'

