version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      - NODE_ENV=development
    tty: true 
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - '8080:8080'
    depends_on:
      - backend
    tty: true
  database:
    image: mongo
    build: ./database
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - ./database/data:/data/db
    restart: always


